services:
  in_api:
    container_name: in_api
    build:
      context: ..
      dockerfile: ./docker/local-dockerfile
    volumes:
      - ..:/api
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      in_db:
        condition: service_healthy
    networks:
      - local-network

  in_db:
    image: mysql:8.0
    restart: always
    container_name: in_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD} # 루트 사용자 암호 설정
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      TZ: Asia/Seoul
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    ports:
      - ${DATABASE_PORT}:3306
    networks:
      - local-network

volumes:
  db:

networks:
  local-network:
    driver: bridge
